server {
    listen 8080;

    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # =========================
    # AUTH SERVICE - 8082
    # =========================

    location /api/auth/ {
        proxy_pass http://auth:8082;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


    # =========================
    # OTHER SERVICES
    # =========================

    # CATALOG - 8081
    location /api/catalog {
        proxy_pass http://catalog:8081;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # BOOKING - 8083
    # location /api/bookings {
    #     proxy_pass http://booking:8083;
    # }

    # REVIEWS - 8083
    # location /api/reviews {
    #     proxy_pass http://booking:8083;
    # }

    # AI INSIGHT - 8084
    # location /api/analyze {
    #     proxy_pass http://ai-insight:8084;
    # }

    # ANALYTICS - 8085
    # location /api/analytics {
    #     proxy_pass http://analytics:8085;
    # }


    # =========================
    # REACT FRONTEND
    # =========================

    location / {
        try_files $uri $uri/ /index.html;
    }
}