FROM golang:1.22-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY main.go .

RUN go build -o notification-worker main.go

FROM alpine:3.20

WORKDIR /app

COPY --from=build /app/notification-worker .

RUN apk add --no-cache procps

HEALTHCHECK --interval=10s --timeout=3s --start-period=10s --retries=5 \
  CMD pgrep notification-worker > /dev/null || exit 1

CMD ["./notification-worker"]